### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by llwt** [bradmartin/nativescript-bottomnavigation#1]
Doing a bit of digging trying to find a material-bottom nav plugin for {N} before I roll one myself. Any chance you found one or have plans to revisit this?

**Comment by bradmartin** [comment]
I need to delete this repo 😄 - Someone took this an inspiration many months ago and actually published it here https://github.com/kobby-sun/nativescript-bottomnavigation. So you can try that one instead.

**Comment by llwt** [comment]
Thanks for the quick response (and all your other {N} stuff)!
